steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - --tag
      - "gcr.io/${PROJECT_ID}/helloworld:${TAG_NAME}"
      - --tag
      - "gcr.io/${PROJECT_ID}/helloworld:latest"
      - "."

images:
  - "gcr.io/${PROJECT_ID}/helloworld:${TAG_NAME}"
  - "gcr.io/${PROJECT_ID}/helloworld:latest"

options:
  logging: CLOUD_LOGGING_ONLY
