# TODO(brett): Move this tooling to custom build image w/dedicated scripts.

substitutions:
  _REG_HOST: us-docker.pkg.dev
  _PROJ_ID: id-me-build
  _DEV_REPO: docker-dev
  _PRD_REPO: docker-release
  _APP: helloworld

  _DEV_IMG: ${_REG_HOST}/${_PROJ_ID}/${_DEV_REPO}/${_APP}
  _PRD_IMG: ${_REG_HOST}/${_PROJ_ID}/${_PRD_REPO}/${_APP}
  _TAG: ${_PR_NUMBER}

  _REGION_US01: us-west2
  _REGION_US02: us-east4

options:
     dynamic_substitutions: true


steps:
  ###
  ## Build Docker image
  ##
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      set -eEu
      if [ "${BRANCH_NAME}" = master ]; then
          echo "====> Skipping build/push step for master branch."
          exit 0
      fi

      echo "====> Building image"
      docker build . \
          -t "${_DEV_IMG}:${_TAG}" \
          -t "${_DEV_IMG}:latest" \

      echo "====> Pushing image"
      docker push "${_DEV_IMG}:${_TAG}"
      docker push "${_DEV_IMG}:latest"

  ###
  ## Deploy image to dev
  ##
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      set -eEu
      if [ "${BRANCH_NAME}" = master ]; then
          echo "====> Skipping dev deploy step for master branch."
          exit 0
      fi

      echo "====> Deploying image '${_DEV_IMG}:${_TAG}"
      gcloud run deploy "${_APP}-dev-pr${_PR_NUMBER}" \
          --image="${_DEV_IMG}:${_TAG}" \
          --region="${_REGION_US01}" \
          --ingress=internal-and-cloud-load-balancing \
          --allow-unauthenticated \

  ###
  ## Promote image to release repo
  ##
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      set -eEux
      if [ "${BRANCH_NAME}" != master ]; then
          echo "====> Skipping production deployment for non-master branch."
          exit 0
      fi

      echo "====> Finding last PR from commit log..."
      pr_num="$$(git log -1 --pretty='format:%s' \
          |grep -i 'pull request' \
          |awk '{print $$4}' \
          |sed 's/#//')"

      if [ -z "$$pr_num" ]; then
          echo "====> Did not find a PR# in HEAD!"
          echo "====> Exiting."
          exit 1
      fi

      echo "====> Promoting image '${_APP}:$$pr_num"
      # Copy from dev repo to release repo
      gcloud container images add-tag \
          "${_DEV_IMG}:$$pr_num" \
          "${_PRD_IMG}:$$pr_num" \

      # Add a 'latest' tag to release repo
      gcloud container images add-tag \
          "${_PRD_IMG}:$$pr_num" \
          "${_PRD_IMG}:latest" \

      # XXX Deploy to production
      for region in ${_REGION_US01} ${_REGION_US02}; do
        echo
        echo "====> Deploying '${_PRD_IMG}:$$pr_num' to $$region"
        gcloud run deploy "${_APP}-prod" \
            --image="${_PRD_IMG}:$$pr_num" \
            --region="$$region" \
            --ingress=internal-and-cloud-load-balancing \
            --allow-unauthenticated
      done
